name: App
description: "Movie App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  google_fonts: ^6.2.1
  provider: ^6.1.5
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  animated_snack_bar: ^0.4.0
  connectivity_plus: ^6.1.4
  flutter_native_splash: ^2.3.10
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  socket_io_client: ^3.1.2
  pull_to_refresh: ^2.0.0
  shimmer: ^3.0.0
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  firebase_auth: ^6.0.2
  flutter_credit_card: ^4.1.0
  payment_card: ^0.0.1
  u_credit_card: ^1.4.0
  loading_animation_widget: ^1.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/aspirant_league.png"
  remove_alpha_ios: true


flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_native_splash:
  color: "#F75423"             # background color for splash
  image: "assets/aspirant_league.png" # show app logo in splash
  android: true
  ios: true
  android_gravity: center      # center the image
  ios_content_mode: scaleAspectFit # maintains aspect ratio on iOS
  fullscreen: true             # full screen splash
  web: false                   # disable for web
