// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVnXCpMLasJIKPHXKN44jLtTI0hkpuY3I',
    appId: '1:148589647851:web:0af4e0ece59e3fc74a2bae',
    messagingSenderId: '148589647851',
    projectId: 'chatly-d3da4',
    authDomain: 'chatly-d3da4.firebaseapp.com',
    storageBucket: 'chatly-d3da4.firebasestorage.app',
    measurementId: 'G-J9S63VXMYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABChT3AHrusGDE3jG5TQGDyW2sM4VESz4',
    appId: '1:148589647851:android:867c13b852ff79d14a2bae',
    messagingSenderId: '148589647851',
    projectId: 'chatly-d3da4',
    storageBucket: 'chatly-d3da4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1_rZmS2_6S2YhDiljoE5G8EQZ1BjYxJc',
    appId: '1:148589647851:ios:57a1e502972fefa24a2bae',
    messagingSenderId: '148589647851',
    projectId: 'chatly-d3da4',
    storageBucket: 'chatly-d3da4.firebasestorage.app',
    iosBundleId: 'com.example.App',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1_rZmS2_6S2YhDiljoE5G8EQZ1BjYxJc',
    appId: '1:148589647851:ios:57a1e502972fefa24a2bae',
    messagingSenderId: '148589647851',
    projectId: 'chatly-d3da4',
    storageBucket: 'chatly-d3da4.firebasestorage.app',
    iosBundleId: 'com.example.App',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVnXCpMLasJIKPHXKN44jLtTI0hkpuY3I',
    appId: '1:148589647851:web:37c6dc6af9f2dacb4a2bae',
    messagingSenderId: '148589647851',
    projectId: 'chatly-d3da4',
    authDomain: 'chatly-d3da4.firebaseapp.com',
    storageBucket: 'chatly-d3da4.firebasestorage.app',
    measurementId: 'G-HFH5X6CK0H',
  );
}
